name: Cut Semantic Release

on:
  push:
    branches:
      - main

jobs:
  generate-release-tag:
    name: generate-release-tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
      packages: read
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20.14

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: First Module
        with:
          working_directory: ./lib/firstModule
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Semantic Release
        uses: cycjimmy/semantic-release-action@v4
        id: Second Module
        with:
          working_directory: ./lib/secondModul
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}


