name: Cut Semantic Release

on:
  push:
    branches:
      - main

jobs:
  generate-release-tag:
    name: generate-release-tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Setup nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20.14

      - name: Install dependencies
        run: npm i

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release -e semantic-release-monorepo

